services:
  # FastAPI Backend Service
  - type: web
    name: gistlover
    runtime: python3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    healthCheckPath: /health
    
    branch: main
    rootDir: .  

  # Streamlit Frontend Service  
  - type: web
    name: gistlover
    runtime: python3
    plan: free  
    buildCommand: pip install -r requirements-frontend.txt
    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: API_BASE_URL
        value: https://blog-tracker-api.onrender.com  
    # Auto-deploy from main branch
    branch: main
    rootDir: . 
